---
apiVersion: v1
appVersion: "2.10.4"
description: |
  An IP address management (IPAM) and data center infrastructure management (DCIM) tool.

  Important; With chart version 3.0.0 the old nginx+gunicorn setup is no more, refer to
  https://github.com/netbox-community/netbox-docker/releases/tag/1.0.0 for more info.
icon: https://raw.githubusercontent.com/digitalocean/netbox/develop/netbox/project-static/img/netbox.ico
name: netbox
version: 3.0.1
