---
apiVersion: v2
name: netbox
description: |
  An IP address management (IPAM) and data center infrastructure management (DCIM) tool.

  Important; With chart version 3.0.0 the old nginx+gunicorn setup is no more, refer to
  https://github.com/netbox-community/netbox-docker/releases/tag/1.0.0 for more info.
icon: https://raw.githubusercontent.com/digitalocean/netbox/develop/netbox/project-static/img/netbox.ico
appVersion: 2.11.4

type: application
version: 3.0.8
maintainers:
  - name: Alexander Olofsson
    email: ace@haxalot.com

dependencies:
  - name: postgresql
    version: ~8.9.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: ~10.6.12
    repository: https://charts.bitnami.com/bitnami
