---
# Default values for netbox.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: netboxcommunity/netbox
  tag: v2.7.8-ldap
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

database:
  ## Database host
  host: localhost

  ## Database port
  port: 5432

  ## Database user
  user: netbox

  ## Database password
  password: netbox

  ## Database name
  database: netbox

redis:
  cluster:
    enabled: false
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false
  password: netbox
  redisPort: 6379

djangoSecret: ''

extraEnv: {}
  # EMAIL_SERVER: localhost
  # EMAIL_PORT: 25
  # EMAIL_USERNAME: netbox
  # EMAIL_TIMEOUT: 5
  # EMAIL_FROM: netbox@example.com
  # NAPALM_USERNAME: ''
  # NAPALM_TIMEOUT: 10
  # MAX_PAGE_SIZE: 1000
  # WEBHOOKS_ENABLED: true

extraSecrets: {}
  # EMAIL_PASSWORD: netbox
  # NAPALM_PASSWORD: ''

superuser:
  name: ''
  email: ''
  apiToken: ''
  password: ''

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

extraVolumes: []

extraVolumeMounts: []
  # - name: extra-music-data
  #   mountPath: /srv/funkwhale/data/music
  #   readOnly: true
  #   existingClaim: volume-claim

persistence:
  enabled: false
  # existingClaim: netbox-data
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 10Gi

worker:
  enabled: true

  replicaCount: 1

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

