---
stages:
  - test
  - deploy

lint:charts:
  image:
    name: codenest/helm
    entrypoint: ["/bin/sh", "-c"]
  stage: test
  script:
    - helm lint charts/*

pages:
  image:
    name: codenest/helm
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
    - mkdir -p public
    - "echo \"User-Agent: *\nDisallow: /\" > ./public/robots.txt"
    - helm init
    - (cd public; helm package ../charts/*)
    - helm repo index public --url ${CI_PAGES_URL}
  artifacts:
    paths:
      - public
  only:
    - master@ananace/charts
