apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "funkwhale.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "funkwhale.name" . }}
    helm.sh/chart: {{ include "funkwhale.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    audio.funkwhale/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "funkwhale.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      audio.funkwhale/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "funkwhale.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        audio.funkwhale/component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "funkwhale.fullname" . }}
          - secretRef:
              name: {{ include "funkwhale.fullname" . }}
          ports:
            - name: api
              containerPort: 5000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          readinessProbe:
            tcpSocket:
              port: http
          volumeMounts:
            - name: data
              mountPath: /srv/funkwhale/data
          {{- range .Values.api.extraVolumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "funkwhale.fullname" . }}-data
    {{- range .Values.api.extraVolumeMounts }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .existingClaim }}
    {{- end }}<Paste>
