apiVersion: v1
kind: Secret
metadata:
  name: {{ include "funkwhale.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "funkwhale.name" . }}
    helm.sh/chart: {{ include "funkwhale.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  CACHE_URL: {{ .Values.redisUrl | b64enc }}
  DATABASE_URL: {{ .Values.dbUrl | b64enc }}
  DJANGO_SECRET_KEY: {{ .Values.djangoSecret | b64enc }}
