apiVersion: v1
kind: Service
metadata:
  name: {{ include "funkwhale.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "funkwhale.name" . }}
    helm.sh/chart: {{ include "funkwhale.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app.kubernetes.io/name: {{ include "funkwhale.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    audio.funkwhale/component: api
