---
apiVersion: v2
appVersion: "1.2.9"
description: A social platform to enjoy and share music
icon: https://funkwhale.audio/favicon.png
name: funkwhale
version: 1.0.0

dependencies:
- name: postgresql
  version: ^12.1.4
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: ^17.3.17
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
