{{- if .Values.ingress.enabled -}}
{{- $fullName := include "radosgw.fullname" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{ include "radosgw.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.dnsName | quote }}
      http:
        paths:
          - path: /
            backend:
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
              service:
                name: {{ $fullName }}
                port: http
{{- else -}}
              serviceName: {{ $fullName }}
              servicePort: http
{{- end -}}
{{- end }}
