{{- if or .Values.secretKey (not .Values.existingSecret) .Values.puppetdb.ssl.key.value .Values.puppetdb.ssl.cert.value .Values.puppetdb.ssl.ca.value .Values.extraSecrets }}
{{- $existing := (lookup "v1" "Secret" .Release.Namespace (include "puppetboard.fullname" .)) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "puppetboard.fullname" . }}
  labels:
    {{- include "puppetboard.labels" . | nindent 4 }}
data:
{{- if .Values.secretKey }}
  SECRET_KEY: {{ .Values.secretKey | b64enc }}
{{- else if not .Values.existingSecret }}
{{-   if and $existing $existing.SECRET_KEY }}
  SECRET_KEY: {{ $existing.SECRET_KEY }}
{{-   else }}
  SECRET_KEY: {{ randAlphaNum 64 | b64enc }}
{{-   end }}
{{- end }}
{{- if .Values.puppetdb.ssl.key.content }}
  PUPPETDB_KEY: {{ .Values.puppetdb.ssl.key.content | b64enc }}
{{- end }}
{{- if .Values.puppetdb.ssl.cert.content }}
  PUPPETDB_CERT: {{ .Values.puppetdb.ssl.cert.content | b64enc }}
{{- end }}
{{- if .Values.puppetdb.ssl.ca.content }}
  PUPPETDB_SSL_VERIFY: {{ .Values.puppetdb.ssl.ca.content | b64enc }}
{{- end }}
{{- range $k, $v := .Values.extraSecrets }}
  {{ $k }}: {{ $v | toString | b64enc }}
{{- end }}
{{- end }}
