---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "synatainer.fullname" . }}
  labels:
    {{- include "synatainer.labels" . | nindent 4 }}
data:
  SYNAPSE_HOST: {{ .Values.synapse.url | default "http://matrix-synapse:8008" | quote }}

{{- range $key, $val := .Values.extraEnv }}
  {{ $key }}: {{ $val | toString | quote }}
{{- end -}}
