---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synatainer.fullname" . }}
  labels:
    {{- include "synatainer.labels" . | nindent 4 }}
data:
  PGPASSWORD: {{ .Values.postgresql.password | toString | b64enc }}
  BEARER_TOKEN: {{ .Values.synapse.token | toString | b64enc }}

{{- range $key, $val := .Values.extraSecrets }}
  {{ $key }}: {{ $val | toString | b64enc }}
{{- end -}}
