{{- if (and .Values.config.mail.password .Values.config.mail.existingSecret) -}}
{{- fail "Can't specify both direct password as well as existing secret for mail" -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.fullname" . }}
  labels:
    {{- include "peertube.labels" . | nindent 4 }}
data:
{{- if (and .Values.externalPostgresql.password (not .Values.externalPostgresql.existingSecret)) }}
  PEERTUBE_DB_PASSWORD: {{ .Values.externalPostgresql.password | b64enc }}
{{- end }}
{{- if (and (not .Values.redis.enabled) .Values.externalRedis.password) }}
  PEERTUBE_REDIS_AUTH: {{ .Values.externalRedis.password | b64enc }}
{{- end }}

{{- if .Values.config.mail.password }}
  PEERTUBE_SMTP_PASSWORD: {{ .Values.config.mail.password | b64enc }}
{{- end }}

{{- if .Values.config.objectStorage.enabled }}
  PEERTUBE_OBJECT_STORAGE_CREDENTIALS_ACCESS_KEY_ID: {{ required "An access key must be provided for object storage" .Values.config.objectStorage.accessKey | b64enc }}
  PEERTUBE_OBJECT_STORAGE_CREDENTIALS_SECRET_ACCESS_KEY: {{ required "A secret key must be provided for object storage" .Values.config.objectStorage.secretKey | b64enc }}
{{- end }}
