---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netbox.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "netbox.name" . }}
    helm.sh/chart: {{ include "netbox.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "netbox.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: app
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configuration.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "netbox.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ include "netbox.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "netbox.fullname" . }}
            - secretRef:
                name: {{ include "netbox.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.persistence.enabled .Values.extraVolumeMounts }}
          volumeMounts:
            - name: netbox-static-files
              mountPath: /opt/netbox/netbox/static
            - name: netbox-config-files
              mountPath: /etc/netbox/config/gunicorn_config.py
              subPath: gunicorn_config.py
              readOnly: true
            - name: netbox-socket
              mountPath: /tmp/netbox
            - name: data
              mountPath: /etc/netbox/media
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
{{- end }}
          {{- end }}
        - name: nginx
          image: "nginx:alpine"
          imagePullPolicy: Always
          command:
            - nginx
            - -c
            - /etc/netbox-nginx/nginx.conf
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
              path: /
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              port: http
              path: /
          volumeMounts:
            - name: netbox-config-files
              mountPath: /etc/netbox-nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: netbox-static-files
              mountPath: /opt/netbox/netbox/static
              readOnly: true
            - name: netbox-socket
              mountPath: /tmp/netbox
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: netbox-config-files
          configMap:
            name: {{ .Chart.Name }}-config-files
        - name: netbox-static-files
          emptyDir: {}
        - name: netbox-socket
          emptyDir: {}
        - name: data
      {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "netbox.fullname" .) }}
      {{- else }}
          emptyDir: {}
      {{- end }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
{{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
