apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netbox.fullname" . }}-front
  labels:
    app.kubernetes.io/name: {{ include "netbox.name" . }}
    helm.sh/chart: {{ include "netbox.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    com.digitalocean.netbox/component: front
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "netbox.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      com.digitalocean.netbox/component: front
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "netbox.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        com.digitalocean.netbox/component: front
    spec:
      initContainers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              cp /etc/netbox-nginx/* /tmp/netbox-nginx
              sed -e 's!http://netbox:8001!http://{{ include "netbox.fullname" . }}-api:8001!' -i /tmp/netbox-nginx/nginx.conf
              cp -r /opt/netbox/netbox/project-static/* \
                 /usr/local/lib/python3.6/site-packages/django/contrib/admin/static/* \
                 /usr/local/lib/python3.6/site-packages/debug_toolbar/static/* \
                 /usr/local/lib/python3.6/site-packages/django_tables2/static/* \
                 /usr/local/lib/python3.6/site-packages/drf_yasg/static/* \
                 /usr/local/lib/python3.6/site-packages/mptt/static/* \
                 /usr/local/lib/python3.6/site-packages/rest_framework/static/* \
                 /tmp/netbox-static 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: netbox-nginx-config
              mountPath: /tmp/netbox-nginx
            - name: netbox-static-files
              mountPath: /tmp/netbox-static
            # - name: netbox-configuration
            #   path: /etc/netbox/config
            #   readOnly: true
            # - name: netbox-initializers
            #   path: /opt/netbox/initializers
            #   readOnly: true
            # - name: netbox-startup-scripts
            #   path: /opt/netbox/startup_scripts
            #   readOnly: true
            # - name: netbox-reports
            #   path: /opt/netbox/reports
            #   readOnly: true
      containers:
        - name: nginx
          image: "nginx:alpine"
          imagePullPolicy: Always
          command:
            - nginx
            - -c
            - /etc/netbox-nginx/nginx.conf
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          volumeMounts:
            - name: netbox-nginx-config
              mountPath: /etc/netbox-nginx
              readOnly: true
            - name: netbox-static-files
              mountPath: /opt/netbox/netbox/static
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: netbox-nginx-config
          emptyDir: {}
        - name: netbox-static-files
          emptyDir: {}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
