---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbox.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "netbox.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "netbox.chart" . }}
data:
{{- if .Values.database }}
  DB_PASSWORD: {{ .Values.database.password | b64enc }}
{{- else if .Values.postgresql.postgresqlPassword }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc }}
{{- end }}
{{- if .Values.djangoSecret }}
  SECRET_KEY: {{ .Values.djangoSecret | b64enc }}
{{- else if not .Values.existingDjangoSecret }}
  SECRET_KEY: {{ randAlphaNum 50 | b64enc }}
{{- end }}

{{- if .Values.superuser.apiToken }}
  SUPERUSER_API_TOKEN: {{ .Values.superuser.apiToken | b64enc }}
{{- end }}
{{- if .Values.superuser.password }}
  SUPERUSER_PASSWORD: {{ .Values.superuser.password | b64enc }}
{{- end }}

{{- range $key, $value := .Values.extraSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
