apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbox.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "netbox.name" . }}
    helm.sh/chart: {{ include "netbox.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  DB_PASSWORD: {{ .Values.database.password | b64enc }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
  SECRET_KEY: {{ .Values.djangoSecret | b64enc }}

  SUPERUSER_API_TOKEN: {{ .Values.superuser.apiToken | b64enc }}
  SUPERUSER_PASSWORD: {{ .Values.superuser.password | b64enc }}

{{- range $key, $value := .Values.extraSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
